sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t docker -f Dockerfile.dev .

script:
  - docker run -e CI=true docker npm run test

deploy:
  provider: elasticbeanstalk
  region: "eu-central-1"
  app: "docker-react"
  env: "docker-react-env"
  bucket_name: "elasticbeanstalk-eu-central-1-329259960010"
  bucket_path: "docker-react"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY